### ISSUE TITLE
Clearly define plasma-mvp branches

### ISSUE THREAD

**Issue by kasima** [omisego/plasma-mvp#114]
- no-confs
- reference
- production
  - 4 IO/4 IO
  - supports tokens
  - fee withdrawal
  - fee structure
  - sparse merkle tree

**Comment by kfichter** [comment]
Agreed on clearly defining each branch.

Should we also clearly define "reference"? We're already pretty far from Vitalik's original spec, so it might be useful to come up with a clear spec for the base Plasma MVP we're building here.

**Comment by kasima** [comment]
Spoke to @DavidKnott about it this morning. He thinks we're just about ready to branch off a `reference` branch. Perhaps after merging #109.

@kfichter – Is there anything else we might want merge before doing that? Do we need to define what we mean by `reference` further?

**Comment by kfichter** [comment]
As per call w/ @kasima, I don't think we need to merge anything else before branching off (maybe testing lang?). Only concern is MVP's underspecification, so I think we should document any significant differences between MVP and our reference implementation.

**Comment by kasima** [comment]
:+1: merging #92 as part of `reference`

**Comment by kfichter** [comment]
Should we close and move discussion to `plasma-contracts`?

**Comment by kasima** [comment]
Yep, this is no longer applicable.
