### ISSUE TITLE
priority queue needs optimizations / benchmarking

### ISSUE THREAD

**Issue by kasima** [omisego/plasma-mvp#117]
This has only been tested to few exits and gas costs go up as exits go up. Need to benchmark, make sure it works, and optimize, if needed.

Primarily concerned with insertions

**Comment by kfichter** [comment]
So we can achieve O(1) `insert` if we implement something like a Fibonacci heap. We're still basically limited by log(n) `delete-min` during the finalization of exits, but that's less of a concern than having a large gas cost be a limiting factor to the *submission* of exits.

**Comment by kfichter** [comment]
Closing as out of scope for MVP.
