### ISSUE TITLE
Update README so users know to use Ganache 1.2.1+

### ISSUE THREAD

**Issue by kfichter** [omisego/plasma-mvp#154]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Motivation for Change

Old versions of Ganache will cause the event listener to crash.

**Comment by jeamick** [comment]
hello @kfichter ,

Do you mean that you need someone to update the repository by installing the last version of ganache and by checking that the version should be the last one ?

is that right ?

If Yes I can commit an pull request about that
Thanks

JM

**Comment by MDSchaeffer** [comment]
Added callout/link for Ganache 1.2.1+ in README, created pull request #164 for this.

**Comment by kfichter** [comment]
Fixed in #164, thanks!
