### ISSUE TITLE
make,error!

### ISSUE THREAD

**Issue by rectinajh** [omisego/plasma-mvp#158]
error: ‘struct leveldb::Options’ has no member named ‘max_file_size’
     __pyx_v_options->max_file_size = __pyx_t_4;
                      ^
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:2: recipe for target 'init' failed

help!
<img width="485" alt="2018-07-19 10 15 05" src="https://user-images.githubusercontent.com/3462559/42917602-cc323970-8b3c-11e8-83bb-a6f743ee5ce0.png">

**Comment by hernandp** [comment]
Post your environment details, please.

**Comment by kfichter** [comment]
Can you look at this and see if it's any help?

https://github.com/wbolster/plyvel/issues/62

**Comment by kfichter** [comment]
Closing for now. If you still have this issue, please let me know and I'll reopen the issue. Thanks!
