### ISSUE TITLE
Server error when calling `omg sendtx`

### ISSUE THREAD

**Issue by dcb9** [omisego/plasma-mvp#177]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

After starting Plasma I tried to create a transaction and submit it to the child chain via the command `omg sendtx`, but it went wrong.

## Expected Behavior

It should be successful.

## Steps to Reproduce

1. [start plasma](https://github.com/omisego/plasma-mvp#starting-plasma)
2. `omg deposit 100 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7`
3. `omg sendtx 1 0 0 0 0 0 0x0 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7 50 0x4B3eC6c9dC67079E82152d6D55d8dd96a8e6AA26 45 3bb369fecdc16b93b99514d8ed9c2e87c5824cf4a6a98d2e8e91b7dd0c063304`

- Full output of error: 
```
Error: {'code': -32000, 'message': 'Server error', 'data': {'type': 'KeyError', 'args': [1], 'message': '1'}}
additional details can be found from the child chain's server output
```
- Child chain output of error:
```
API Exception: {'type': 'KeyError', 'args': (1,), 'message': '1'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/json_rpc-1.10.8-py3.6.egg/jsonrpc/manager.py", line 112, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "plasma/child_chain/server.py", line 20, in <lambda>
    dispatcher["apply_transaction"] = lambda transaction: child_chain.apply_transaction(rlp.decode(utils.decode_hex(transaction), Transaction))
  File "/Users/bob/Documents/omisego/plasma-mvp/plasma/child_chain/child_chain.py", line 36, in apply_transaction
    self.chain.validate_transaction(tx, self.current_block.spent_utxos)
  File "/Users/bob/Documents/omisego/plasma-mvp/plasma_core/chain.py", line 63, in validate_transaction
    input_tx = self.blocks[blknum].transaction_set[txindex]
KeyError: 1
127.0.0.1 - - [30/Aug/2018 09:38:34] "POST /jsonrpc HTTP/1.1" 200 -
```
- Command that caused error: 
`
omg sendtx 1 0 0 0 0 0 0x0 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7 50 0x4B3eC6c9dC67079E82152d6D55d8dd96a8e6AA26 45 3bb369fecdc16b93b99514d8ed9c2e87c5824cf4a6a98d2e8e91b7dd0c063304
`
- Code that caused error: `0`

## System Specs

- python version: 3.6.5
- pyetherem version: 
- environment (output of running `pip freeze`):
atomicwrites==1.2.0
attrs==18.1.0
click==6.7
configparser==3.5.0
dnet==1.12
enum34==1.1.6
ethereum==2.3.0
flake8==3.5.0
funcsigs==1.0.2
json-rpc==1.10.8
mccabe==0.6.1
meld3==1.0.2
more-itertools==4.3.0
pathlib2==2.3.2
pbr==4.2.0
pdfminer==20140328
plasma==0.0.0
pluggy==0.7.1
plyvel==1.0.4
py==1.6.0
py-solc==3.1.0
pycodestyle==2.3.1
pyflakes==1.6.0
pytest==3.7.3
rlp==0.6.0
semantic-version==2.6.0
six==1.11.0
stevedore==1.29.0
virtualenv==16.0.0
virtualenv-clone==0.3.0
virtualenvwrapper==4.8.2
web3==4.5.0
Werkzeug==0.14.1
- operating system: Mac OS 10.13.6

**Comment by bg1156** [comment]
https://github.com/omisego/plasma-mvp/blob/master/.gitignore

**Comment by dcb9** [comment]
@bg1156 have you had this bug?

**Comment by kfichter** [comment]
Hi, what version Ganache CLI are you using?

**Comment by dcb9** [comment]
```
$ ganache-cli --version
Ganache CLI v6.1.8 (ganache-core: 2.2.1)
```

**Comment by kfichter** [comment]
If you shut down ganache and retry, does the same problem pop up?

**Comment by dcb9** [comment]
It's so weird, yesterday i restart ganache and retry, but i got same problem. after restarting my system it works now.

Thanks

**Comment by kfichter** [comment]
This does reveal another bug, though. I'll make an issue for it. Thank you for the PR!
