### ISSUE TITLE
when is the child-chain's first block created?

### ISSUE THREAD

**Issue by code-brewer** [omisego/plasma-mvp#207]
hi all.  I am not familiar with plasma and need help on some concepts.

### First question:
Does the first-block created at the moment that plasmat-contract deployed or at the point that first deposit() call from client ? 
 
### Second question:
   Does there only one instance of   plasmat-contract on root-chain event if there is multilple direct child-chain ?

**Comment by code-brewer** [comment]
So much appreciated to your comment.  I asked these question  because i'm blocked while trying to use this [ https://github.com/matterinc/PlasmaContract/blob/master/contracts/PlasmaParent.sol  ]( https://github.com/matterinc/PlasmaContract/blob/master/contracts  )Plasma implementation.  It seem to use array to store all child-chain, but i am not sure.

**Comment by boolafish** [comment]
Did a quick look, it doesn't seem like to be multiple child-chain though. Can you point out where makes you feel like that?
