### ISSUE TITLE
KeyError: 'abi' when making root

### ISSUE THREAD

**Issue by nickemmons** [omisego/plasma-mvp#21]
When running `make root-chain` I am getting this error:

```
 File "/workspace/plasma-mvp/plasma/root_chain/deployer.py", line 35, in compile_contract
    abi = compiled_sol['contracts'][file_name][contract_name]['abi']
KeyError: 'abi'
make: *** [root-chain] Error 1
```

Haven't been able to find anything about why this might be happening.  Any thoughts?

**Comment by federicobond** [comment]
Have you made any modifications to the contract? Could be the result of a failed compilation.

**Comment by nickemmons** [comment]
I did change `pragma solidity 0.4.18;` in the contracts to `pragma solidity >=0.4.18;` because I was getting an error related to that.  Do you think that could be the cause?

**Comment by kfichter** [comment]
This error occurs when using `solc` 0.4.19. What version of `solc` are you using?

**Comment by nickemmons** [comment]
I was using `solc` 0.4.19.  Switching to `solc` 0.4.18 fixed it.  Closing the issue
