### ISSUE TITLE
Package name taken on PyPI

### ISSUE THREAD

**Issue by sergei-maertens** [omisego/plasma-mvp#5]
I was curious to see if the package was available on PyPI, and it turns out it's not, see https://pypi.python.org/pypi/plasma

Other than that, a quick look at the `setup.py` also shows the `long_description` as the contents of `Readme.md`, which will lose its formatting since PyPI by default assumes .rst instead of markdown.

**Comment by federicobond** [comment]
Alternatives:

 * eth-plasma
 * ethereum-plasma
 * pyplasma

**Comment by alexphelps** [comment]
eth-plasma or ethereum-plasma would work imho.

**Comment by pmaji** [comment]
@alexphelps +1 vote for eth-plasma

**Comment by kfichter** [comment]
Closing until we decide to publish to PyPI (although I agree with `eth-plasma`).
