### ISSUE TITLE
Bonded Exits

### ISSUE THREAD

**Issue by AdityaSripal** [omisego/plasma-mvp#58]
StartExit should require a bond proportional to the UTXO being exited to provide a stronger disincentive for invalid exit transactions and eliminates the burden on users to be vigilant of fraudulent exits from previous owners.
Since a successful challengeExit will transfer the bond to the sender of the challengeExit transaction, one can broadcast their confirmSigs to "fraud bounty hunters" who can challenge fraudelent exits on the user's behalf and claim the bond as a reward.

- Blockchain @ Berkeley Researcher

**Comment by kfichter** [comment]
Is the bond necessarily a % of the exit? It seems like we just need to set bond >= cost of challenging (incl gas, labor, etc.) in order to properly incentivise challenges.

**Comment by AdityaSripal** [comment]
I don't think it's necessary. The benefit of making the bond a % of exit is that large UTXO's get more attention from bounty hunters.

I think either way is fine.

**Comment by kfichter** [comment]
I think we just need to incentivise challenges in general and ensure that all exits *can* be challenged. As long as those two conditions are met it shouldn't matter how large the exit is.

**Comment by AdityaSripal** [comment]
For sure, I have two PR's up implementing both ways to bond. Up to you guys which you prefer.

I currently set a constant bond of 10000 Wei, but more work needs to be done to find out what the constant bond should be to reliably be higher than the gas cost of calling challengeExit.
