### ISSUE TITLE
"key" parameter, not using at this function.

### ISSUE THREAD

**Issue by ggs134** [omisego/plasma-mvp#75]
https://github.com/omisego/plasma-mvp/blob/1683070b28bb64b0193f7dd4220957849fd6d317/plasma/client/client.py#L37

What is the purpose of "key" parameter?
Is is not used at the body of function.

**Comment by kfichter** [comment]
This is an artifact from a previous commit and should be removed.

**Comment by kfichter** [comment]
Fixed in #87
