### ISSUE TITLE
Deposit blocks are not signed before being included in the list of blocks.

### ISSUE THREAD

**Issue by ggs134** [omisego/plasma-mvp#81]
In child_chain.py,

If a block in <current_block> is signed,  then this block is appended to <blocks = {}> variable.

It is block signing process.

However, when deposit tx and make a block, this block does not signed but included in <blocks = {}> variables.

I think signing process should be implemented at child_chain.py, apply_deposit() function.

And merkle, too.

**Comment by paulperegud** [comment]
Deposit blocks are signed by depositor and their correctness is guaranteed by Ethereum. Signature of operator does not add anything of value.

**Comment by kfichter** [comment]
Closing as operator does not need to sign deposit blocks
