### ISSUE TITLE
Client Command Broken Because of the RootChain Contract Changes

### ISSUE THREAD

**Issue by maxweng** [omisego/plasma-mvp#89]
Although all tests run through without problems for me, some of the client commands, like `deposit` and `withdraw` are broken in the command line. I guess it's because RootChain.sol is updated. I've fixed the `deposit` command, which I changed the line 38 in file plasma/client/client.py
from: 
`        self.root_chain.deposit(rlp.encode(transaction, UnsignedTransaction), transact={'from': '0x' + transaction.newowner1.hex(), 'value': transaction.amount1})`
to:
`        self.root_chain.deposit(transact={'from': '0x' + transaction.newowner1.hex(), 'value': transaction.amount1})`

I also tried to fix the `withdraw` command, but got `revert` error when running against the Ganache-cli. Anyone has a similar problem?

**Comment by kfichter** [comment]
Thanks! Closing as fixed in #91
